default_language_version:
  python: python3

repos:

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        files: '^.*\.py'
        args: ["--line-length", "79"]

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)

  - repo: https://github.com/PyCQA/flake8
    rev: 3.8.4
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
      - id: mypy
        types: [python]
        args: [--strict, --ignore-missing-imports]
        
