dataset:
  drive_url: "https://drive.google.com/drive/folders/18lNjZPYKLmd7w-UX7GwepHAy2R-3YP3W"
  name: "stead"
  download_path: "dataset"
  bifurcating_path: "bifurcating/raw/database.hdf5"
  single_path: "single/raw/database.hdf5"
  train_size: 0.75
  val_size: 0.15
  test_size: 0.1
  batch_size: 16

baseline:
  transformer_embedding_dim: 1024
  transformer_num_heads: 8
  transformer_feedforward_dim: 1024
  transformer_num_layers: 4
  learning_rate: 0.001

trainer:
  max_epochs: 100
  patience: 10
  ckpt_path: "ckpt"