dataset:
  drive_url: "https://drive.google.com/drive/folders/18lNjZPYKLmd7w-UX7GwepHAy2R-3YP3W"
  download_path: "dataset"
  bifurcating_id: 1U1UZR1nlIhlhzgGcPisASbTugn3iO7G5
  single_id: 1b4Nhc3PUL_ZAChoOCRpCK4Nh-eKL66-v
  train_size: 0.75
  val_size: 0.15
  test_size: 0.1
  batch_size: 4
  features_size_limit: 200

baseline:
  transformer_embedding_dim: 16
  transformer_num_heads: 4
  transformer_feedforward_dim: 16
  transformer_num_layers: 1
  learning_rate: 0.001
  features_size_limit: 200 # Warning: must be the same of dataset.features_size_limit

gatr:
  hidden_size: 16
  num_attention_heads: 4
  learning_rate: 0.0001
  num_backbone_layers: 1
  features_size_limit: 200 # Warning: must be the same of dataset.features_size_limit

trainer:
  wandb_api_key: "41e4ba7425e35355cd4456863ed4cd9c73c084a3"
  max_epochs: 15
  patience: 3
  ckpt_path: "ckpt"
  wandb_project: "Vessel-Geometric-Transformers"
  min_delta: 0.00001
  resume_training: False

optuna:
  n_trials: 3
  seed: 42
  